#!/usr/bin/env python3
"""Generate LaTeX numbers and tables from machine-readable analysis outputs."""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd


PRIMARY = {
    "NREM": "PSD (published)",
    "REM": "Catch22 filtered (adapted)",
}


def _one(frame: pd.DataFrame, **criteria: object) -> pd.Series:
    selected = frame
    for column, value in criteria.items():
        selected = selected[selected[column] == value]
    if len(selected) != 1:
        raise ValueError(f"Expected one row for {criteria}, found {len(selected)}")
    return selected.iloc[0]


def _camel(text: str) -> str:
    return "".join(part.capitalize() for part in text.replace("_", " ").split())


def _command(name: str, value: str) -> str:
    return rf"\newcommand{{\{name}}}{{{value}}}"


def _auc(value: float) -> str:
    return f"{value:.3f}"


def _pct(value: float) -> str:
    return f"{100 * value:.1f}\%"


def generate(results_dir: Path, legacy_dir: Path, destination: Path) -> None:
    estimates = pd.read_csv(results_dir / "targeted-estimates.csv")
    differences = pd.read_csv(results_dir / "paired-model-baseline-differences.csv")
    pairs = pd.read_csv(results_dir / "site-pair-summary.csv")
    sites = pd.read_csv(results_dir / "primary-site-estimates.csv")
    composition = pd.read_csv(results_dir / "stage-specific-composition.csv")
    legacy = pd.read_csv(legacy_dir / "fig5-validation-summary.csv")
    lodo = pd.read_csv(legacy_dir / "fig5-lodo-subject-inference.csv")

    commands: list[str] = [
        "% Generated by analysis/dream-consciousness/generate_manuscript_assets.py.",
        "% Do not edit numerical values by hand.",
    ]

    for stage, family in PRIMARY.items():
        prefix = stage.capitalize()
        for estimand, suffix in {
            "pooled": "Pooled",
            "site_macro": "SiteMacro",
            "within_pair_weighted": "WithinPair",
            "site_macro_fold_conditioned": "FoldSiteMacro",
            "within_pair_weighted_fold_conditioned": "FoldWithinPair",
        }.items():
            row = _one(
                estimates,
                analysis="eeg_model",
                stage=stage,
                feature_family=family,
                weighting="record",
                estimand=estimand,
            )
            commands.extend(
                [
                    _command(f"{prefix}{suffix}AUC", _auc(row.estimate)),
                    _command(f"{prefix}{suffix}Low", _auc(row.ci_low)),
                    _command(f"{prefix}{suffix}High", _auc(row.ci_high)),
                ]
            )

        delta = _one(
            differences,
            stage=stage,
            feature_family=family,
            baseline="record_prevalence",
            weighting="record",
            estimand="within_pair_weighted_fold_conditioned",
        )
        commands.extend(
            [
                _command(f"{prefix}FoldDelta", _auc(delta.estimate)),
                _command(f"{prefix}FoldDeltaLow", _auc(delta.ci_low)),
                _command(f"{prefix}FoldDeltaHigh", _auc(delta.ci_high)),
            ]
        )

        pair = _one(pairs, stage=stage, feature_family=family)
        commands.extend(
            [
                _command(f"{prefix}WithinPairFraction", _pct(pair.within_pair_fraction)),
                _command(f"{prefix}CrossPairFraction", _pct(pair.cross_pair_fraction)),
                _command(f"{prefix}CrossConcordance", _auc(pair.cross_concordance)),
            ]
        )

        random_row = _one(
            legacy,
            task="experience",
            stage=stage,
            feature_family=family,
            regime="random_record",
        )
        participant_row = _one(
            legacy,
            task="experience",
            stage=stage,
            feature_family=family,
            regime="subject_held_out",
        )
        laboratory_row = _one(
            legacy,
            task="experience",
            stage=stage,
            feature_family=family,
            regime="laboratory_held_out",
        )
        commands.extend(
            [
                _command(f"{prefix}RandomAUC", _auc(random_row.mean_auroc)),
                _command(f"{prefix}LegacyParticipantAUC", _auc(participant_row.mean_auroc)),
                _command(f"{prefix}LaboratoryAUC", _auc(laboratory_row.mean_auroc)),
            ]
        )

        site_only = _one(
            estimates,
            analysis="site_only_record_prevalence",
            stage=stage,
            feature_family="No EEG features",
            weighting="record",
            estimand="pooled",
        )
        commands.extend(
            [
                _command(f"{prefix}SiteOnlyPooledAUC", _auc(site_only.estimate)),
                _command(f"{prefix}SiteOnlyPooledLow", _auc(site_only.ci_low)),
                _command(f"{prefix}SiteOnlyPooledHigh", _auc(site_only.ci_high)),
            ]
        )

    rem_sensitivity = estimates[
        (estimates.analysis == "sensitivity_rem_excluding_turku")
        & (estimates.weighting == "record")
    ]
    for estimand, suffix in {
        "pooled": "Pooled",
        "within_pair_weighted": "WithinPair",
        "within_pair_weighted_fold_conditioned": "FoldWithinPair",
    }.items():
        row = _one(rem_sensitivity, estimand=estimand)
        commands.extend(
            [
                _command(f"RemNoTurku{suffix}AUC", _auc(row.estimate)),
                _command(f"RemNoTurku{suffix}Low", _auc(row.ci_low)),
                _command(f"RemNoTurku{suffix}High", _auc(row.ci_high)),
            ]
        )

    for stage in ("NREM", "REM"):
        identity = legacy[
            (legacy.task == "dataset_identity") & (legacy.stage == stage)
        ]
        commands.extend(
            [
                _command(f"{stage.capitalize()}IdentityMin", _auc(identity.mean_auroc.min())),
                _command(f"{stage.capitalize()}IdentityMax", _auc(identity.mean_auroc.max())),
            ]
        )

    published_identity = legacy[
        (legacy.task == "dataset_identity")
        & legacy.feature_family.isin(
            [
                "PSD (published)",
                "Catch22 broadband (published)",
                "Catch22 filtered (adapted)",
            ]
        )
    ]
    commands.extend(
        [
            _command("PublishedIdentityMin", _auc(published_identity.mean_auroc.min())),
            _command("PublishedIdentityMax", _auc(published_identity.mean_auroc.max())),
        ]
    )

    for label, family in {
        "Raw": "Temporal irreversibility",
        "Surrogate": "Surrogate-normalized irreversibility",
    }.items():
        row = _one(
            legacy,
            task="experience",
            stage="REM",
            feature_family=family,
            regime="laboratory_held_out",
        )
        commands.append(_command(f"Rem{label}IrrevLaboratoryAUC", _auc(row.mean_auroc)))

    macro_lodo = lodo[lodo.held_out_dataset == "MACRO_MEAN"]
    for stage, family in PRIMARY.items():
        row = _one(macro_lodo, stage=stage, feature_family=family)
        commands.append(
            _command(
                f"{stage.capitalize()}LaboratoryParticipantEqualAUC",
                _auc(row.subject_equal_auroc),
            )
        )

    destination.mkdir(parents=True, exist_ok=True)
    (destination / "generated_results.tex").write_text(
        "\n".join(commands) + "\n", encoding="utf-8"
    )

    composition_rows = [
        "% Generated stage-specific composition rows.",
    ]
    for _, row in composition.iterrows():
        flag = "$^{*}$" if row.no_experience < 5 else ""
        composition_rows.append(
            f"{row.stage} & {row.display_name}{flag} & {int(row.participants)} & "
            f"{int(row.records)} & {int(row.experience)} & {int(row.no_experience)} & "
            f"{100 * row.experience_prevalence:.1f}\\% \\\\"
        )
    composition_rows.append(r"\bottomrule")
    (destination / "generated_composition_rows.tex").write_text(
        "\n".join(composition_rows) + "\n", encoding="utf-8"
    )

    site_rows = ["% Generated primary within-site AUROC rows."]
    selected_sites = sites[sites.weighting == "record"]
    for _, row in selected_sites.iterrows():
        site_rows.append(
            f"{row.stage} & {row.display_name} & {int(row.participants)} & "
            f"{int(row.experience)} & {int(row.no_experience)} & "
            f"{row.estimate:.3f} [{row.ci_low:.3f}, {row.ci_high:.3f}] \\\\"
        )
    site_rows.append(r"\bottomrule")
    (destination / "generated_primary_site_rows.tex").write_text(
        "\n".join(site_rows) + "\n", encoding="utf-8"
    )

    secondary_rows = ["% Generated complete site-conditioned feature-family rows."]
    feature_order = [
        "PSD (published)",
        "Catch22 broadband (published)",
        "Catch22 filtered (adapted)",
        "Riemannian covariance",
        "Log-Euclidean domain alignment",
        "Temporal irreversibility",
        "Surrogate-normalized irreversibility",
    ]
    for stage in ("NREM", "REM"):
        for family in feature_order:
            row = _one(
                estimates,
                analysis="eeg_model",
                stage=stage,
                feature_family=family,
                weighting="record",
                estimand="within_pair_weighted",
            )
            secondary_rows.append(
                f"{stage} & {family.replace('Catch22', 'Catch22 ')} & "
                f"{row.estimate:.3f} [{row.ci_low:.3f}, {row.ci_high:.3f}] \\\\"
            )
    secondary_rows.append(r"\bottomrule")
    (destination / "generated_secondary_rows.tex").write_text(
        "\n".join(secondary_rows) + "\n", encoding="utf-8"
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--results-dir",
        type=Path,
        default=Path("outputs/dream-consciousness/targeted-revision"),
    )
    parser.add_argument(
        "--legacy-dir",
        type=Path,
        default=Path("outputs/dream-consciousness"),
    )
    parser.add_argument(
        "--destination",
        type=Path,
        default=Path("manuscript/dream-generalization"),
    )
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    generate(args.results_dir, args.legacy_dir, args.destination)
